name-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 Features'
    labels: ['feature', 'enhancement']
  - title: '🐛 Fixes'
    labels: ['bug', 'fix']
  - title: '🧰 Maintenance'
    labels: ['chore', 'build', 'ci', 'docs']
  - title: '🔐 Security'
    labels: ['security']

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'

template: |
  ## Changes

  $CHANGES

  ## Contributors
  $CONTRIBUTORS
