repository:
  default_branch: main

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - CI (Linux)
          - CI (Windows)
          - CI (macOS)
      enforce_admins: true
      restrictions: null 