[package]
name = "nxsh_builtins"
version = "0.1.0"
edition = "2021"

[dependencies]
nxsh_core = { path = "../nxsh_core" }
nxsh_hal = { path = "../nxsh_hal" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] } 
dirs-next = "2" 
aes-gcm = { version = "0.10", features = ["aes", "rand_core"] }
rand = "0.8"
base64 = "0.21" 
tabled = "0.12"
pulldown-cmark = "0.10"
ansi_term = "0.12" 
tokio = { version = "1", features = ["fs", "macros", "rt-multi-thread"] }
git2 = "0.18"
pcre2 = { version = "0.2", features = ["utf8"] }
rayon = "1.8" 
regex = "1"
meval = "0.2"
tar = "0.4"
flate2 = { version = "1.0", features = ["gzip"] }
bzip2 = "0.4"
zstd = { version = "0.13", features = ["zstdmt"] }
indicatif = "0.17"
walkdir = "2" 
bitflags = "1" 
jmespath = "0.3" 
ahash = "0.8" 
thiserror = "1"
once_cell = "1"
libc = "0.2"
signal-hook = { version = "0.3", features = ["iterator"] }
term_size = "0.3"
which = "4.4"
sysinfo = { version = "0.29", features = ["multithread"] }
crossterm = { version = "0.27", features = ["event-stream"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
ratatui = "0.24"
atty = "0.2"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls"] }
url = "2"
xz2 = "0.1"
zip = "0.6"

[dev-dependencies]
tempfile = "3" 