[package]
name = "nxsh_builtins"
version = "0.1.0"
edition = "2021"

[dependencies]
nxsh_core = { path = "../nxsh_core" }
nxsh_hal = { path = "../nxsh_hal" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] } 
dirs-next = "2" 
aes-gcm = { version = "0.10", features = ["aes", "rand_core"] }
rand = "0.8"
base64 = "0.21" 
tabled = "0.12"
pulldown-cmark = "0.10"
ansi_term = "0.12" 
tokio = { version = "1", features = ["fs", "macros", "rt-multi-thread"] }
git2 = "0.18"
humansize = "2" 
pcre2 = { version = "0.2", features = ["utf8"] }
rayon = "1.8" 