[workspace]
resolver = "2"
members = [
    "crates/nxsh_core",
    "crates/nxsh_parser",
    "crates/nxsh_ui",
    "crates/nxsh_hal",
    # "crates/nxsh_plugin",  # Temporarily disabled
    "crates/nxsh_builtins",
    "crates/nxsh_cli",
]

[workspace.dependencies]
chrono = { version = "0.4", features = ["local-offset"] } 
filetime = "0.2"
walkdir = "2"
windows-sys = "0.48"
rand = "0.8"
term_size = "0.3" 