[advisories]
ignore = [
    # Unmaintained crates in indirect deps; tracked for migration
    "RUSTSEC-2021-0139", # ansi_term unmaintained
    "RUSTSEC-2024-0375", # atty unmaintained
    "RUSTSEC-2021-0145", # atty potential unaligned read
    "RUSTSEC-2020-0016", # net2 deprecated
    "RUSTSEC-2024-0436", # paste unmaintained
    "RUSTSEC-2024-0370", # proc-macro-error unmaintained
    "RUSTSEC-2025-0017", # trust-dns rebrand
    # Vulnerabilities with planned upgrades
    "RUSTSEC-2024-0421", # idna <1.0.3 in transitive deps
    "RUSTSEC-2025-0047", # slab <0.4.11 (will be bumped)
]

[bans]
multiple-versions = "allow"
deny = [
    { name = "openssl" }
]

[sources]
unknown-git = "deny"

[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "Unicode-3.0",
  "Unicode-DFS-2016",
  "BSL-1.0",
  "CC0-1.0",
  "MPL-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "Zlib",
  "ISC",
]
confidence-threshold = 0.8