[package]
name = "nxsh_core"
version = "0.1.0"
edition = "2021"

[features]
default = []
jit = ["cranelift-codegen", "cranelift-frontend"]
object-pipe = []

[dependencies]
anyhow = "1"
dashmap = "5"
once_cell = "1.19"

[target.'cfg(feature = "jit")'.dependencies]
cranelift-codegen = "0.104"
cranelift-frontend = "0.104" 

[target.'cfg(unix)'.dependencies]
nix = { version = "0.27", default-features = false, features = ["fcntl", "unistd"] } 