[package]
name = "nxsh_core"
version = "0.1.0"
edition = "2021"

[features]
default = []
jit = ["cranelift-codegen", "cranelift-frontend"]
object-pipe = []

[dependencies]
anyhow = "1"

[target.'cfg(feature = "jit")'.dependencies]
cranelift-codegen = "0.104"
cranelift-frontend = "0.104" 