[package]
name = "nxsh_hal"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
anyhow = "1"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.27", default-features = false, features = ["fs", "process", "signal"] }
seccomp-sys = "0.1" 