name: NexusShell CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build and test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Show rustc/cargo version
        run: |
          rustc -V
          cargo -V

      - name: Cargo check (all features)
        run: cargo check --workspace --all-features

      - name: Cargo test (all features)
        run: cargo test --workspace --all-features --no-fail-fast

      - name: Cargo build release (all features)
        run: cargo build --workspace --all-features --release

  clippy:
    name: Clippy (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run clippy (diagnostics only)
        run: cargo clippy --workspace --all-features -- -A clippy::all

  fmt:
    name: Format check (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain (with rustfmt)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check

  deny:
    name: Cargo Deny (dependency audit)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cargo Deny
        uses: EmbarkStudios/cargo-deny-action@v1

  i18n:
    name: I18N compile check (ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install gettext
        run: sudo apt-get update && sudo apt-get install -y gettext
      - name: Compile translations (inline)
        run: |
          set -euo pipefail
          find i18n/po -name '*.po' | while read -r po; do \
            lang=$(basename "$(dirname "$po")"); \
            out="i18n/mo/$lang/LC_MESSAGES/nxsh.mo"; \
            mkdir -p "$(dirname "$out")"; \
            msgfmt "$po" -o "$out"; \
          done

  size-gate:
    name: Size gate (busybox-min)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run size report (threshold)
        shell: pwsh
        run: |
          $env:NXSH_SIZE_MAX = "1572864"
          cargo build -p nxsh_cli --no-default-features --features busybox-min --profile release-small
          $bin = "target/release-small/nxsh.exe"
          $size = (Get-Item $bin).Length
          if ($size -gt [int]$env:NXSH_SIZE_MAX) { echo "Size gate failed: $size > $env:NXSH_SIZE_MAX"; exit 2 } else { echo "Size gate OK ($size bytes)" }
          "{`"size_bytes`":$size}" | Set-Content -Encoding UTF8 size_report_local.json
      - name: Upload size report
        uses: actions/upload-artifact@v4
        with:
          name: size-report
          path: size_report_local.json
  theme-validate:
    name: Theme validation (python)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate themes via nxsh_ui
        run: cargo run -p nxsh_ui --bin theme_validator_test -- --dir assets/themes --out-format json --out reports/theme_validation.json --strict

  coverage:
    name: Coverage (ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain (llvm-tools)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov
      - name: Generate coverage (lcov)
        run: |
          cargo llvm-cov clean --workspace
          cargo llvm-cov --workspace --all-features --no-report
          cargo llvm-cov --workspace --all-features --lcov --output-path coverage.lcov
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage.lcov
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.lcov
          fail_ci_if_error: false