name: License Audit

on:
  schedule:
    - cron: '0 0 1 * *' # 1st of every month
  workflow_dispatch:

jobs:
  license-compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v1

      - name: Run cargo-deny license check
        run: cargo deny check licenses --locked

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: license-audit-report
          path: target/cargo-deny/deny.toml 