name: Security and Dependency Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install cargo-audit
        run: cargo install cargo-audit --locked
      - name: Run cargo audit
        run: cargo audit -D warnings

  cargo-vet:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install cargo-vet
        run: cargo install cargo-vet --locked
      - name: Run cargo vet (best-effort)
        run: cargo vet check

  cargo-udeps:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust (nightly)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Install cargo-udeps
        run: cargo install cargo-udeps --locked
      - name: Run cargo udeps (best-effort)
        run: cargo +nightly udeps --all-targets --workspace

