name: Security (cargo deny)

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-deny
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-deny
      - name: cargo deny check
        run: cargo deny --all-features --workspace check 