[package]
name = "nxsh_plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
nxsh_core = { path = "../nxsh_core" }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wasmtime = { version = "14", default-features = false, features = ["async"] }
wasmtime-wasi = "14"
ring = "0.16"
base64 = "0.21"
reqwest = { version = "0.11", features=["blocking", "rustls-tls"] }
semver = "1" 